Run qrexec daemon and redirect rpc calls to stubdom
QubesOS/qubes-core-admin pull request #383
Opened 2021-01-20 11:55 UTC by easydozen

QubesOS/qubes-issues#5802

2021-01-27 05:03 UTC, marmarek requested changes

2021-01-27 05:03 UTC, marmarek commented on qubes/vm/qubesvm.py
> +                            self.default_user]
You sure? I don't think there are any non-root users in stubdomain...

2021-01-27 05:04 UTC, marmarek commented
And also please add tests for the newly introduced cases.

2021-01-28 12:22 UTC, easydozen commented
> And also please add tests for the newly introduced cases.
I've added one subtest for run_service here. Another one provided by QubesOS/qubes-app-linux-usb-proxy/pull/22.
Did I miss something?

2021-02-15 10:58 UTC, marmarek requested changes

2021-02-15 10:58 UTC, marmarek commented on qubes/vm/qubesvm.py
>          if not self.is_qrexec_running():
This is a bit unfortunate - it checks if qrexec is connected to the actual domain, not to the stubdomain, even if the call is requested to the stubdomain (`stubdom=True`).

2021-06-19 19:43 UTC, marmarek commented
And now this needs `Requires: xen-hvm-stubdom-linux-full` in the spec file.

2021-06-20 14:59 UTC, marmarek commented on rpm_spec/core-dom0.spec.in
> -Requires:       xen-hvm-stubdom-linux >= 1.0.13
No, both are needed

2021-06-23 04:21 UTC, marmarek approved these changes

2021-06-23 13:25 UTC, merged