Wrap coroutine in Task before passing to asyncio.wait
QubesOS/qubes-core-admin pull request #508
Opened 2023-01-01 00:14 UTC by DemiMarie

Needed in Python 3.11+.

2023-01-12 16:30 UTC, rustybird commented
Just in case you haven't already seen this and decided it's okay, the [documentation for `asyncio.Task()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task) says

> Use the high-level [`asyncio.create_task()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task) function to create Tasks, or the low-level [`loop.create_task()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_task) or [`ensure_future()`](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future) functions. Manual instantiation of Tasks is discouraged.

2023-01-18 22:56 UTC, marmarek requested changes

2023-01-18 22:56 UTC, marmarek commented on qubes/utils.py
> +    coros = [asyncio.Task(val) for val in values if asyncio.iscoroutine(val)]
```suggestion
    coros = [asyncio.create_task(val) for val in values if asyncio.iscoroutine(val)]
```

2023-01-19 04:01 UTC, marmarek approved these changes

2023-01-19 05:53 UTC, merged