Extension to store features starting with vm-config in qubesdb
QubesOS/qubes-core-admin pull request #527
Opened 2023-04-13 22:01 UTC by marmarta

Idea: to have a simple way of transmitting certain external (qubes-level) settings to inside a vm.

2023-04-14 00:17 UTC, marmarek requested changes
You also need to add the extension to setup.py. And to the spec file.

2023-04-14 00:17 UTC, marmarek commented on qubes/ext/vm_config.py
> +    /qubes-vm-config/ tree.
I'd drop `qubes-` part, qubesdb paths have quite low length limit, so lets leave more space for the actual name.

2023-04-14 00:17 UTC, marmarek commented on qubes/ext/vm_config.py
> +            service = feature[len(PREFIX):]
It isn't really a service

2023-04-14 00:17 UTC, marmarek commented on qubes/ext/vm_config.py
> +        service = feature[len(PREFIX):]
Here too

2023-04-15 14:05 UTC, marmarek commented
PipelineRetry

2023-04-18 12:07 UTC, marmarta commented
PipelineRetryFailed

2023-04-27 13:47 UTC, merged