ext/audio: update audiovm qubesdb entry
QubesOS/qubes-core-admin pull request #582
Opened 2024-03-04 12:38 UTC by fepitre

2024-03-04 13:32 UTC, marmarek requested changes

2024-03-04 13:32 UTC, marmarek commented on qubes/ext/audio.py
> +            self.set_qubesdb_audiovm(subject)
This should be under `if subject.is_running()`

2024-03-04 13:34 UTC, marmarek commented
oh, and also a lot of tests failed

2024-03-04 15:33 UTC, fepitre commented
PipelineRetry

2024-03-04 16:10 UTC, fepitre commented
PipelineRetry

2024-03-04 16:11 UTC, fepitre commented
PipelineRetry

2024-03-04 16:12 UTC, fepitre commented
PipelineRetry

2024-03-04 18:34 UTC, DemiMarie reviewed
Nits

2024-03-04 18:34 UTC, DemiMarie commented on qubes/ext/audio.py
> +            if getattr(domain, "audiovm", None) and domain.audiovm == vm:
```suggestion
            if getattr(domain, "audiovm", None) == vm:
```

should be equivalent

2024-03-04 18:34 UTC, DemiMarie commented on qubes/ext/audio.py
> +                )
```suggestion
        audiovm = getattr(vm, "audiovm", None):
        if audiovm is not None:
            if audiovm != vm and audiovm.is_running():
                vm.untrusted_qdb.write(
                    "/qubes-audio-domain-xid", str(audiovm.xid)
                )
```

2024-03-29 15:25 UTC, marmarek approved these changes

2024-03-29 16:03 UTC, merged