Implementing -h & --help for qvm-console-dispvm
QubesOS/qubes-core-admin pull request #605
Opened 2024-07-04 21:41 UTC by alimirjamali

fixes: https://github.com/QubesOS/qubes-issues/issues/8019

2024-07-04 21:42 UTC, alimirjamali commented
This PR is about closing arguments in Github comments. Focusing on more important issues.

2024-07-04 22:46 UTC, DemiMarie approved these changes

2024-07-05 15:01 UTC, marmarek requested changes
Add also info about `--help` / `-h` to the help itself...

2024-07-05 15:14 UTC, marmarek approved these changes

2024-07-05 15:28 UTC, merged