Introduce LocalVM to extract BaseVM being smaller class
QubesOS/qubes-core-admin pull request #637
Opened 2024-11-23 09:10 UTC by fepitre

It prepares the work for RemoteVM.

2024-11-23 09:11 UTC, fepitre commented
@marmarek can you run openQA on it please?

2024-11-23 11:10 UTC, marmarek commented
Sure, I can, but I think you may want to first take care of unit tests, this one looks like a real issue:
```
  File "/home/user/builds/QubesOS/qubes-core-admin/qubes/vm/__init__.py", line 403, in load_extras
    for parent in self.xml.xpath("./devices"):
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'xpath'
```

2024-11-25 10:10 UTC, fepitre commented
> Sure, I can, but I think you may want to first take care of unit tests, this one looks like a real issue:
> 
> ```
>   File "/home/user/builds/QubesOS/qubes-core-admin/qubes/vm/__init__.py", line 403, in load_extras
>     for parent in self.xml.xpath("./devices"):
>                   ^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'xpath'
> ```

Fixed.

2025-03-26 18:04 UTC, marmarek requested changes

2025-03-26 18:04 UTC, marmarek commented on qubes/vm/__init__.py
> +        # pylint: disable=no-member
and here

2025-03-26 18:04 UTC, marmarek commented on qubes/vm/__init__.py
> +        if not issubclass(vmclass, LocalVM):
While default to LocalVM makes sense, should it really forbid using RemoteVM as some property value?

2025-03-26 18:04 UTC, marmarek commented on qubes/vm/adminvm.py
> +        if not isinstance(other, LocalVM):
This should remain BaseVM, otherwise sorting VM objects will not work with RemoteVM

2025-03-27 00:16 UTC, marmarek commented
PipelineRetry

2025-03-27 01:39 UTC, marmarek approved these changes

2025-03-27 01:59 UTC, merged